export const Sitios = {
    sites : [{
        id: 1,
        nombre: "Machu Pichu",
        continente: "America",
        descripcion: "Sitio arqueológico inca más sobresaliente debido a su creativo diseño urbano, la belleza de su arquitectura y el fino trabajo en piedra de sus construcciones",
        pais: "Perú",
        imagen: "https://th.bing.com/th/id/OIP.bCsIINKJfbPIU3inoeohWwHaE8?pid=ImgDet&rs=1",
        valoracion: 7,
    },
    {
        id: 2,
        nombre: "Cristo Redentor",
        continente: "America",
        descripcion: "El Cristo Redentor o Cristo del Corcovado es una estatua art déco que representa a Jesús de Nazaret, con los brazos abiertos, mostrando a la ciudad de Río de Janeiro",
        pais: "Brasil",
        imagen: "https://www.la-razon.com/wp-content/uploads/2020/08/958767-01-02.jpg",
        valoracion: 8,
    },
    {
        id: 3,
        nombre: "Cancún",
        continente: "America",
        descripcion: "Ubicado en la costa noreste del estado de Quintana Roo, destaca por su belleza escénica y paisajística en torno a sus playas, así como la gran variedad de flora y fauna",
        pais: "Mexico",
        imagen: "https://www.fodors.com/wp-content/uploads/2022/04/Hero-Not2DoCancun-shutterstock_1063645616.jpg",
        valoracion: 9,
    },
    {
        id: 4,
        nombre: "Obelisco de Buenos Aires",
        continente: "America",
        descripcion: "El Obelisco de Buenos Aires es un monumento histórico de 67,5 metros de altura, considerado un ícono de la Ciudad de Buenos Aires, la capital de Argentina.",
        pais: "Argentina",
        imagen: "https://4.bp.blogspot.com/-lNQ7IfeCHF0/Vw6ThuZKszI/AAAAAAAAAAk/JKGDAiIidyIFx6lCR4wa6KeeTfSBjg70ACLcB/s1600/Obelisco_en_Buenos_Aires.JPG",
        valoracion: 4,
    },
    {
        id: 5,
        nombre: "Santuaria de las Lajas",
        continente: "America",
        descripcion: "El Santuario de Nuestra Señora del Rosario de Las Lajas es un templo y basílica para el culto cristiano y veneración de Nuestra Señora de Las Lajas.",
        pais: "Colombia",
        imagen: "https://pelecanus.com.co/wp-content/uploads/2019/08/Nari%C3%B1o5.jpg",
        valoracion: 8,
    },
    {
        id: 6,
        nombre: "Islas Galápagos",
        continente: "America",
        descripcion: "Estan conformadas por 13 islas, en ellas se encuentran varios edificios volcánicos, los principales son: Isabela y Fernandina.",
        pais: "Ecuador",
        imagen: "https://viajes.nationalgeographic.com.es/medio/2019/08/02/un-eden-remoto_a8e2f1ce_1254x837.jpg",
        valoracion: 9,
    },
    //Europa
    {
        id: 7,
        nombre: "Coliseo de Roma",
        continente: "Europa",
        descripcion: "El Coliseo se convirtió en el mayor anfiteatro romano, con una estructura elíptica de 188 metros de longitud, 156 metros de ancho y 57 metros de altura.",
        pais: "Italia",
        imagen: "https://historia.nationalgeographic.com.es/medio/2018/03/01/coliseo-romano_16022ed4_1280x853.jpg",
        valoracion: 8,
    },
    {
        id: 8,
        nombre: "Santa Sofía",
        continente: "Europa",
        descripcion: "Fue construida durante el mandato de Justiniano entre los años 532 y 537 y es una de las obras maestras del arte bizantino.",
        pais: "Turquía",
        imagen: "https://i.pinimg.com/originals/08/20/bc/0820bc9a1ddceacedde235c24f768d4c.jpg",
        valoracion: 6,
    },
    {
        id: 9,
        nombre: "Torre Eifel",
        continente: "Europa",
        descripcion: "La Torre Eiffel es una construcción de hierro de 300 metros creada para la Exposición Universal de París de 1889. Es el símbolo más representativo de París.",
        pais: "Francia",
        imagen: "http://farm1.static.flickr.com/105/255497291_05dadba0d6.jpg?v=0",
        valoracion: 9,
    },
    {
        id: 10,
        nombre: "Catedral de San Basilio",
        continente: "Europa",
        descripcion: "Construida entre 1555 y 1561 bajo el encargo de Iván el Terrible, la Catedral de San Basilio es el símbolo de Moscú y de toda Rusia.",
        pais: "Rusia",
        imagen: "https://www.bautrip.com/images/front/moscu.jpg",
        valoracion: 9,
    },
    {
        id: 11,
        nombre: "Stonehenge",
        continente: "Europa",
        descripcion: "Stonehenge es un monumento megalítico tipo crómlech, además de otros elementos como hoyos, fosos, montículos, etc., construido entre el final del Neolítico y principios de la Edad del Bronce",
        pais: "Inglaterra",
        imagen: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTJckl6Sq8HTKw_TrQbPq8se489OKvxUNdVmkunXP5beFVapKT6N_psYd_m57HkEGMsKnEUd_27cFEOyDsFTLKlSg",
        valoracion: 9,
    },
    {
        id: 12,
        nombre: "Zurich",
        continente: "Europa",
        descripcion: "La ciudad de Zúrich, un centro bancario y financiero global, se encuentra al norte del lago de Zúrich en el norte de Suiza.",
        pais: "Suiza",
        imagen: "https://media.istockphoto.com/id/1291781729/es/foto/zurich.jpg?s=612x612&w=0&k=20&c=bhGUGnQopUGxkDzFC2BEZQ_6735SZi-EZ38AAb0FFJE=",
        valoracion: 10,
    },
    //Asia
    {
        id: 13,
        nombre: "Muralla China",
        continente: "Asia",
        descripcion: "La ciudad de Zúrich, un centro bancario y financiero global, se encuentra al norte del lago de Zúrich en el norte de Suiza.",
        pais: "China",
        imagen: "https://viajerosocultos.com/wp-content/uploads/2020/09/the-great-wall.jpg",
        valoracion: 7,
    },
    {
        id: 14,
        nombre: "Taj Mahal",
        continente: "Asia",
        descripcion: "El Taj Mahal es considerado el más bello ejemplo de palacio, estilo que combina elementos de las arquitecturas islámica,​ persa,​ india e incluso turca.​",
        pais: "India",
        imagen: "https://www.entornoturistico.com/wp-content/uploads/2022/09/Que%CC%81-es-el-Taj-Mahal.jpg",
        valoracion: 10,
    },
    {
        id: 15,
        nombre: "Petra",
        continente: "Asia",
        descripcion: "Petra es un importante enclave arqueológico en Jordania,su nombre es idóneo, esta ciudad fue excavada y esculpida en la piedra.",
        pais: "Jordania",
        imagen: "https://images.memphistours.com/large/320597035_petra%204.jpg",
        valoracion: 7,
    },
    {
        id: 16,
        nombre: "Jardines de la Bahia",
        continente: "Asia",
        descripcion: "Los Jardines de la Bahía constituyen el mayor parque de Singapur y se han convertido, por mérito propio, en el símbolo de la ciudad y en su atracción más popular.",
        pais: "Singapur",
        imagen: "https://jardinessinfronteras.files.wordpress.com/2021/01/gardens-by-the-bay_-1.jpg?w=946",
        valoracion: 9,
    },
    {
        id: 17,
        nombre: "Tokyo",
        continente: "Asia",
        descripcion: "Tokio es uno de los centros urbanos más importantes del planeta. Es uno de los principales centros financieros y la capital política de Japón.",
        pais: "Japón",
        imagen: "https://www.gotokyo.org/es/plan/tokyo-outline/images/main.jpg",
        valoracion: 8,
    },
    {
        id: 18,
        nombre: "Bangkok",
        continente: "Asia",
        descripcion: "Bangkok es la capital de Tailandia y su ciudad más importante con una población de más de 8 millones de habitantes.",
        pais: "Tailandia",
        imagen: "https://imagenes.elpais.com/resizer/pKpsAzeO1aqa2M1a-6AIp_ZbxH0=/1960x1103/cloudfront-eu-central-1.images.arcpublishing.com/prisa/VXSEYFTVUFDGPJH6BZFVCGH6OU.jpg",
        valoracion: 9,
    }
]
}